- name: Bring up infrastructure
  terraform:
      project_path: terraform
      state: present
      # force_init is available in 2.6
      # force_init: yes

- name: Refresh inventory
  meta: refresh_inventory
