- hosts: localhost
  gather_facts: no
  connection: local
  tags:
      - provisioning
  tasks:
      - include: tasks/terraform.yaml

- hosts: gluster-demo
  become: yes
  become_method: sudo
  tasks:
      - include: tasks/hosts.yaml

- hosts: gluster
  become: yes
  become_method: sudo
  vars_files:
    - vars/gluster.yaml
  roles:
    - glusterfs
  tasks:
      - include: tasks/mounts.yaml
      - include: tasks/gluster.yaml

- hosts: app
  become: yes
  become_method: sudo
  tags:
      - client
  vars_files:
      - vars/gluster.yaml
  tasks:
      - include: tasks/gluster_client.yaml
