- name: Delete servers
  hosts: localhost
  tasks:
      - name: Server Delete (FRN)
        os_server:
          name: "{{ item }}"
          state: absent
          cloud: demo-frn
        with_items:
            - frn-host-dmz
            - frn-host-a
            - frn-host-b
      - name: Server Delete (COR)
        os_server:
          name: "{{ item }}"
          state: absent
          cloud: demo-cor
        with_items:
            - cor-host-dmz
            - cor-host-a
            - cor-host-b
- name: Delete ports
  hosts: localhost
  tags: ports
  vars:
      - state: absent
  tasks:
      - include: tasks/ports.yaml

- name: Delete routers
  hosts: localhost
  tags: router
  vars:
      - state: absent
  tasks:
      - include: tasks/router.yaml
      # - name: Delete router (COR)
      #   os_router:
      #       name: cor-router
      #       cloud: demo-frn
      #       state: absent
- name: Delete networks
  hosts: localhost
  tags: network
  vars:
      - state: absent
  tasks:
      - include: tasks/secgroups.yaml
      - include: tasks/network.yaml