- name: Router (FRN)
  tags: networking
  when: state != 'absent'
  os_router:
      name: frn-router
      cloud: demo-frn
      state: "{{ state }}"
      network: internet
      interfaces:
          - frn-subnet-a
          - frn-subnet-b
          - frn-subnet-dmz

- name: Router (COR)
  tags: networking
  when: state != 'absent'
  os_router:
      name: cor-router
      cloud: demo-cor
      state: "{{ state }}"
      network: internet
      interfaces:
          - cor-subnet-a
          - cor-subnet-b
          - cor-subnet-dmz

- name: Router delete (FRN)
  when: state == 'absent'
  os_router:
      name: frn-router
      cloud: demo-frn
      state: "{{ state }}"

- name: Router delete (COR)
  when: state == 'absent'
  os_router:
      name: cor-router
      cloud: demo-cor
      state: "{{ state }}"
  
- name: Set static routes (COR)
  when: state == 'present'
  command: openstack --os-cloud demo-cor router set  cor-router --route destination=192.168.1.0/24,gateway=192.168.11.10
  register: result
  failed_when: result.rc !=0 and 'Duplicate' not in result.stderr
      
- name: Set static routes (COR)
  when: state == 'present'
  command: openstack --os-cloud demo-cor router set cor-router --route destination=192.168.2.0/24,gateway=192.168.11.10
  register: result
  failed_when: result.rc !=0 and 'Duplicate' not in result.stderr

- name: Set static routes (COR)
  when: state == 'present'
  command: openstack --os-cloud demo-cor router set  cor-router --route destination=192.168.10.0/24,gateway=192.168.11.10
  register: result
  failed_when: result.rc !=0 and 'Duplicate' not in result.stderr

- name: Set static routes (FRN)
  when: state == 'present'
  command: openstack --os-cloud demo-frn router set frn-router --route destination=192.168.3.0/24,gateway=192.168.10.10
  register: result
  failed_when: result.rc !=0 and 'Duplicate' not in result.stderr
      
- name: Set static routes (FRN)
  when: state == 'present'
  command: openstack --os-cloud demo-frn router set frn-router --route destination=192.168.4.0/24,gateway=192.168.10.10
  register: result
  failed_when: result.rc !=0 and 'Duplicate' not in result.stderr

- name: Set static routes (FRN)
  when: state == 'present'
  command: openstack --os-cloud demo-frn router set frn-router --route destination=192.168.11.0/24,gateway=192.168.10.10
  register: result
  failed_when: result.rc !=0 and 'Duplicate' not in result.stderr

